# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-17 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botapp', '0007_auto_20180307_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandupUserSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_was_done', models.TextField(blank=True)),
                ('current_task', models.TextField(blank=True)),
                ('next_task', models.TextField(blank=True)),
                ('problems', models.TextField(blank=True)),
                ('distractions', models.TextField(blank=True)),
                ('standup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agileapp.Standup')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.UserProfile')),
            ],
        ),
    ]
