# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-20 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standupusersummary',
            old_name='distractions',
            new_name='general_notes',
        ),
        migrations.RemoveField(
            model_name='standupusersummary',
            name='problems',
        ),
    ]
