from datetime import date
import xml.etree.ElementTree as ET


def get_upwork_report():
    today = date.today().strftime('%Y%m%d')
    return {'auth_user': {'first_name': 'Mike',
                          'last_name': 'Bell',
                          'timezone': 'America/New_York',
                          'timezone_offset': '-14400'},
            'server_time': 1489659419,
            'table': {'cols': [{'label': 'worked_on', 'type': 'date'},
                               {'label': 'provider_id', 'type': 'string'},
                               {'label': 'provider_name', 'type': 'string'},
                               {'label': 'hours', 'type': 'number'},
                               {'label': 'memo', 'type': 'string'}],
                      'rows': [{'c': [{'v': today},
                                      {'v': 'jsmith'},
                                      {'v': 'John Smith'},
                                      {'v': '0.166667'},
                                      {'v': 'No memo'}]},
                               {'c': [{'v': today},
                                      {'v': 'vpupkin'},
                                      {'v': 'Vasya Pupkin'},
                                      {'v': '2'},
                                      {'v': '[IOS-96]'}]},
                               {'c': [{'v': today},
                                      {'v': 'bgodunov'},
                                      {'v': 'Boris Godunov'},
                                      {'v': '3.5'},
                                      {'v': '[IOS-153] Create Xcode configurations for support build flavors'}]},
                               {'c': [{'v': today},
                                      {'v': 'dasha'},
                                      {'v': 'Dasha Rasteryasha'},
                                      {'v': '0.5'},
                                      {'v': 'IOS-838'}]},
                               {'c': [{'v': today},
                                      {'v': 'denis'},
                                      {'v': 'Denis'},
                                      {'v': '1.5'},
                                      {'v': 'WEB-336'}]},
                               ]}}


def get_smon_report():
    from_time = int(date.today().strftime('%s'))
    to_time = from_time + 3600

    result = [{'employmentId': 72690,
               'from': from_time,
               'id': '5794a3a2-b52b-40f0-a4a3-3647c4103313',
               'note': 'BACK-813',
               'offline': False,
               'projectId': '935fc1c7-4657-3102-4380-abf65977f11e',
               'task': None,
               'to': to_time},
              {'employmentId': 72691,
               'from': from_time,
               'id': '3388cfbe-638c-4172-b18e-22acb51f4ee1',
               'note': 'BACK-813',
               'offline': False,
               'projectId': '935fc1c7-4657-3102-4380-abf65977f11e',
               'task': None,
               'to': to_time},
              {'employmentId': 72691,
               'from': from_time,
               'id': 'fc559b7c-58d5-4bcd-850f-6a1fc539d65d',
               'note': 'Meeting',
               'offline': False,
               'projectId': '935fc1c7-4657-3102-4380-abf65977f11e',
               'task': None,
               'to': to_time}]

    return result


def load_jira_issue(issue_id):
    j = {'expand': 'renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations',
         'fields': {'aggregateprogress': {'percent': 2,
                                          'progress': 600,
                                          'total': 28800},
                    'aggregatetimeestimate': 28200,
                    'aggregatetimeoriginalestimate': 28800,
                    'aggregatetimespent': 600,
                    'assignee': {'accountId': '557058:5cd74ba3-a3e5-429e-9ea9-a5226bf0a678',
                                 'active': True,
                                 'avatarUrls': {},
                                 'displayName': 'Yevhenii V',
                                 'emailAddress': 'jenny@example.com',
                                 'key': 'jenny.z',
                                 'name': 'yevhenii.v',
                                 'self': 'https://gettipsi.atlassian.net/rest/api/2/user?useIOSme=yevhenii.v',
                                 'timeZone': 'Europe/Kiev'},
                    'attachment': [],
                    'comment': {'comments': [],
                                'maxResults': 0,
                                'startAt': 0,
                                'total': 0},
                    'components': [],
                    'created': '2018-01-03T09:03:44.692-0500',
                    'creator': {'accountId': '557058:ae90c24e-e4d4-4737-8586-e6b98f68bb15',
                                'active': True,
                                'avatarUrls': {},
                                'displayName': 'Dasha D',
                                'emailAddress': 'dasha.d@example.com',
                                'key': 'darya.d',
                                'name': 'darya.d',
                                'self': 'https://gettipsi.atlassian.net/rest/api/2/user?useIOSme=darya.d',
                                'timeZone': 'Europe/Minsk'},
                    'description': 'description 1',
                    'duedate': None,
                    'environment': None,
                    'fixVersions': [{'archived': False,
                                     'description': '',
                                     'id': '14832',
                                     'name': '1.4',
                                     'releaseDate': '2018-01-13',
                                     'released': False,
                                     'self': 'https://gettipsi.atlassian.net/rest/api/2/version/14832'}],
                    'issuelinks': [],
                    'issuetype': {'avatarId': 10418,
                                  'description': 'A task that needs to be done.',
                                  'iconUrl': 'https://gettipsi.atlassian.net/secure/viewavatar?size=xsmall&avatarId=10418&avatarType=issuetype',
                                  'id': '3',
                                  'name': 'Task',
                                  'self': 'https://gettipsi.atlassian.net/rest/api/2/issuetype/3',
                                  'subtask': False},
                    'labels': [],
                    'lastViewed': '2018-01-04T10:52:00.819-0500',
                    'priority': {'iconUrl': 'https://gettipsi.atlassian.net/images/icons/priorities/major.svg',
                                 'id': '3',
                                 'name': 'Major',
                                 'self': 'https://gettipsi.atlassian.net/rest/api/2/priority/3'},
                    'progress': {'percent': 2, 'progress': 600, 'total': 28800},
                    'project': {'avatarUrls': {},
                                'id': '10600',
                                'key': 'IOS',
                                'name': 'React Native App',
                                'projectTypeKey': 'software',
                                'self': 'https://gettipsi.atlassian.net/rest/api/2/project/10600'},
                    'reporter': {'accountId': '557058:ae90c24e-e4d4-4737-8586-e6b98f68bb15',
                                 'active': True,
                                 'avatarUrls': {},
                                 'displayName': 'Dasha Demidenko',
                                 'emailAddress': 'dasha.demidenko@example.com',
                                 'key': 'darya.d',
                                 'name': 'darya.d',
                                 'self': 'https://gettipsi.atlassian.net/rest/api/2/user?useIOSme=darya.d',
                                 'timeZone': 'Europe/Minsk'},
                    'resolution': None,
                    'resolutiondate': None,
                    'security': None,
                    'status': {'description': 'This issue is being actively worked on at the moment by the assignee.',
                               'iconUrl': 'https://gettipsi.atlassian.net/images/icons/statuses/inprogress.png',
                               'id': '3',
                               'name': 'In Progress',
                               'self': 'https://gettipsi.atlassian.net/rest/api/2/status/3',
                               'statusCategory': {'coloIOSme': 'yellow',
                                                  'id': 4,
                                                  'key': 'indeterminate',
                                                  'name': 'In Progress',
                                                  'self': 'https://gettipsi.atlassian.net/rest/api/2/statuscategory/4'}},
                    'subtasks': [],
                    'summary': 'Add an error on adding more than 25 products to shopping cart',
                    'timeestimate': 28200,
                    'timeoriginalestimate': 28800,
                    'timespent': 600,
                    'timetracking': {'originalEstimate': '1d',
                                     'originalEstimateSeconds': 28800,
                                     'remainingEstimate': '7h 50m',
                                     'remainingEstimateSeconds': 28200,
                                     'timeSpent': '10m',
                                     'timeSpentSeconds': 600},
                    'updated': '2018-01-04T10:52:00.298-0500',
                    'versions': [],
                    'votes': {'hasVoted': False,
                              'self': 'https://gettipsi.atlassian.net/rest/api/2/issue/{}/votes'.format(issue_id),
                              'votes': 0},
                    'watches': {'isWatching': False,
                                'self': 'https://gettipsi.atlassian.net/rest/api/2/issue/{}/watchers'.format(issue_id),
                                'watchCount': 1},
                    'worklog': {'maxResults': 20,
                                'startAt': 0,
                                'total': 1,
                                'worklogs': []},
                    'workratio': 2},
         'id': '12345',
         'key': issue_id,
         'self': 'https://gettipsi.atlassian.net/rest/api/latest/issue/12345'}
    return j
