# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:20
from __future__ import unicode_literals

import botapp.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_system', models.IntegerField(choices=[(0, b'jira'), (1, b'github')], default=botapp.enums.IssueSystem(0))),
                ('issue_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('service_type', models.IntegerField(choices=[(0, b'tipsi'), (1, b'upwork'), (2, b'hipchat'), (3, b'jira')])),
            ],
        ),
        migrations.CreateModel(
            name='UpworkWorklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('hours', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botapp.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='upworkworklog',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='user_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accounts', to='botapp.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set([('issue_system', 'issue_id')]),
        ),
    ]
