# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_auto_20170310_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='service_type',
            field=models.IntegerField(choices=[(0, b'tipsi'), (1, b'upwork'), (2, b'hipchat'), (3, b'jira'), (4, b'gitlab'), (5, b'github')]),
        ),
    ]
