# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_auto_20170523_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpworkWorklog',
            new_name='Worklog',
        ),
        migrations.AddField(
            model_name='worklog',
            name='worklog_system',
            field=models.IntegerField(choices=[(0, b'upwork'), (2, b'smon')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='service_type',
            field=models.IntegerField(
                choices=[(0, b'tipsi'), (1, b'upwork'), (2, b'hipchat'), (3, b'jira'),
                         (4, b'gitlab'), (5, b'github'), (6, b'smon')]),
        ),
        migrations.AddField(
            model_name='worklog',
            name='from_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='to_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
