# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_auto_20170601_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('user_profiles', models.ManyToManyField(to='botapp.UserProfile')),
            ],
        ),
    ]
