# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-07 12:37
from __future__ import unicode_literals

import botapp.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0007_auto_20180307_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_system',
            field=models.IntegerField(choices=[(0, 'jira'), (1, 'github')], default=botapp.enums.IssueSystem(0)),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='service_type',
            field=models.IntegerField(choices=[(0, 'tipsi'), (1, 'upwork'), (2, 'hipchat'), (3, 'jira'), (4, 'gitlab'), (5, 'github'), (6, 'smon')]),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='worklog_system',
            field=models.IntegerField(choices=[(0, 'upwork'), (2, 'smon')]),
        ),
    ]
