# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0008_auto_20180807_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccount',
            name='service_type',
            field=models.IntegerField(choices=[(0, 'system'), (1, 'upwork'), (2, 'hipchat'), (3, 'jira'), (4, 'gitlab'), (5, 'github'), (6, 'smon')]),
        ),
    ]
