# Generated by Django 3.1.12 on 2021-07-07 17:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0009_auto_20180815_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='worklog_system',
            field=models.IntegerField(choices=[(0, 'upwork'), (2, 'smon'), (3, 'jira')]),
        ),
    ]
