# Generated by Django 3.1.12 on 2021-07-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0011_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='uniq_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
