# Generated by Django 3.1.12 on 2021-07-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0012_worklog_uniq_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='custom_work_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
