# Generated by Django 3.1.12 on 2021-07-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0013_worklog_custom_work_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='remote_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
