# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 19:50
from __future__ import unicode_literals

import botapp.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botapp', '0003_auto_20170523_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=40, unique=True)),
                ('short_id', models.CharField(max_length=11)),
                ('title', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('author_email', models.CharField(blank=True, max_length=255)),
                ('authored_date', models.DateTimeField(blank=True, null=True)),
                ('committer_name', models.CharField(blank=True, max_length=255)),
                ('committer_email', models.CharField(blank=True, max_length=255)),
                ('committed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('additions', models.IntegerField(blank=True, null=True)),
                ('deletions', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('author_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_commits', to='botapp.UserProfile')),
                ('committer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merged_commits', to='botapp.UserProfile')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botapp.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='GitProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('hosting', models.IntegerField(choices=[(0, b'gitlab'), (1, b'github')], default=botapp.enums.GitHosting(0))),
            ],
        ),
        migrations.AddField(
            model_name='gitcommit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gitapp.GitProject'),
        ),
    ]
