# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='branch',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='gitproject',
            name='project_url',
            field=models.URLField(blank=True),
        ),
    ]
