# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-07 12:37
from __future__ import unicode_literals

import botapp.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitapp', '0004_auto_20180307_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitproject',
            name='hosting',
            field=models.IntegerField(choices=[(0, 'gitlab'), (1, 'github')], default=botapp.enums.GitHosting(0)),
        ),
    ]
