# Generated by Django 2.2 on 2021-03-05 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitapp', '0005_auto_20180807_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcommit',
            name='issue',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='botapp.Issue',
            ),
        ),
    ]
